from app.models.employee import Employee
from app.models.organization import Organization

organizations = [
    Organization(1, "AcmeCorp"),
    Organization(2, "BetaTech"),
    Organization(3, "Infosys"),
    Organization(4, "TCS"),
    Organization(5, "Google"),
]

employees = [
    Employee(1, "Aarav", "Sharma", "aarav.sharma@acmecorp.com", "HR", "Manager", "NY", "Active", 1),
    Employee(2, "Bhavin", "Joshi", "bhavin.joshi@acmecorp.com", "Engineering", "Developer", "SF", "Terminated", 1),
    Employee(3, "Charvi", "Mehta", "charvi.mehta@betatech.com", "HR", "Lead", "LA", "Terminated", 2),
    Employee(4, "Dinesh", "Rao", "dinesh.rao@acmecorp.com", "Finance", "Analyst", "NY", "Not started", 1),
    Employee(5, "Esha", "Desai", "esha.desai@acmecorp.com", "Marketing", "Coordinator", "Boston", "Active", 1),
    Employee(6, "Farhan", "Ali", "farhan.ali@tcs.com", "IT", "Support Engineer", "Mumbai", "Not started", 4),
    Employee(7, "Gauri", "Kapoor", "gauri.kapoor@infosys.com", "Engineering", "Developer", "Bangalore", "Terminated", 3),
    Employee(8, "Harsh", "Patel", "harsh.patel@acmecorp.com", "Engineering", "Lead", "Chicago", "Active", 1),
    Employee(9, "Ishita", "Verma", "ishita.verma@tcs.com", "HR", "Executive", "Pune", "Active", 4),
    Employee(10, "Jay", "Kumar", "jay.kumar@google.com", "AI Research", "Scientist", "Mountain View", "Not started", 5),
    Employee(11, "Kavya", "Singh", "kavya.singh@infosys.com", "QA", "Tester", "Chennai", "Active", 3),
    Employee(12, "Laksh", "Reddy", "laksh.reddy@google.com", "Security", "Engineer", "NY", "Terminated", 5),
    Employee(13, "Meera", "Yadav", "meera.yadav@acmecorp.com", "Admin", "Assistant", "Dallas", "Active", 1),
    Employee(14, "Nikhil", "Bansal", "nikhil.bansal@tcs.com", "Development", "Intern", "Delhi", "Not started", 4),
    Employee(15, "Ojasvi", "Pandey", "ojasvi.pandey@betatech.com", "Engineering", "Architect", "Austin", "Active", 2),
    Employee(16, "Pranav", "Ghosh", "pranav.ghosh@infosys.com", "Finance", "Manager", "Hyderabad", "Active", 3),
    Employee(17, "Riya", "Chauhan", "riya.chauhan@google.com", "HR", "Analyst", "London", "Terminated", 5),
    Employee(18, "Sahil", "Agarwal", "sahil.agarwal@acmecorp.com", "Sales", "Executive", "NY", "Active", 1),
    Employee(19, "Tanvi", "Saxena", "tanvi.saxena@betatech.com", "Support", "Engineer", "Chicago", "Not started", 2),
    Employee(20, "Uday", "Rana", "uday.rana@tcs.com", "Admin", "Executive", "Kolkata", "Active", 4),
    Employee(21, "Vaishnavi", "Naik", "vaishnavi.naik@infosys.com", "IT", "Support Engineer", "Mysore", "Not started", 3),
    Employee(22, "Wasim", "Iqbal", "wasim.iqbal@google.com", "Engineering", "Intern", "San Jose", "Not started", 5),
    Employee(23, "Xiya", "Kulkarni", "xiya.kulkarni@acmecorp.com", "HR", "Lead", "Denver", "Active", 1),
    Employee(24, "Yuvraj", "Tiwari", "yuvraj.tiwari@tcs.com", "HR", "Recruiter", "Mumbai", "Terminated", 4),
    Employee(25, "Zara", "Bhatt", "zara.bhatt@betatech.com", "Development", "Developer", "Seattle", "Active", 2),
    Employee(26, "Aditya", "Shetty", "aditya.shetty@google.com", "Marketing", "Specialist", "NY", "Not started", 5),
    Employee(27, "Bhumika", "Mishra", "bhumika.mishra@acmecorp.com", "Legal", "Advisor", "Houston", "Not started", 1),
    Employee(28, "Chirag", "Sinha", "chirag.sinha@infosys.com", "QA", "Lead", "Bangalore", "Active", 3),
    Employee(29, "Divya", "Rawat", "divya.rawat@tcs.com", "Admin", "Coordinator", "Chennai", "Active", 4),
    Employee(30, "Eshan", "Gill", "eshan.gill@betatech.com", "Engineering", "Tester", "Atlanta", "Terminated", 2),
    Employee(31, "Fatima", "Nair", "fatima.nair@google.com", "AI", "Engineer", "Zurich", "Active", 5),
    Employee(32, "Gagan", "Malik", "gagan.malik@infosys.com", "Support", "Executive", "Pune", "Not started", 3),
    Employee(33, "Heena", "Rathod", "heena.rathod@acmecorp.com", "Security", "Officer", "NY", "Active", 1),
    Employee(34, "Imran", "Dubey", "imran.dubey@tcs.com", "Engineering", "Manager", "Mumbai", "Not started", 4),
    Employee(35, "Jhanvi", "Rana", "jhanvi.rana@betatech.com", "Engineering", "Manager", "Austin", "Not started", 2),
    Employee(36, "Kiran", "Das", "kiran.das@google.com", "Finance", "Analyst", "Seattle", "Terminated", 5),
    Employee(37, "Lalit", "Iyer", "lalit.iyer@infosys.com", "HR", "Manager", "Mysore", "Active", 3),
    Employee(38, "Manisha", "Talwar", "manisha.talwar@acmecorp.com", "Sales", "Lead", "Chicago", "Active", 1),
    Employee(39, "Naveen", "Pathak", "naveen.pathak@tcs.com", "Development", "Engineer", "Pune", "Not started", 4),
    Employee(40, "Oviya", "Paul", "oviya.paul@betatech.com", "Support", "Executive", "Atlanta", "Active", 2),
    Employee(41, "Pankaj", "Dwivedi", "pankaj.dwivedi@tcs.com", "Engineering", "Developer", "Chennai", "Terminated", 4),
    Employee(42, "Rachna", "Mohanty", "rachna.mohanty@acmecorp.com", "QA", "Tester", "Denver", "Active", 1),
    Employee(43, "Saurabh", "Kale", "saurabh.kale@infosys.com", "IT", "Support Engineer", "Delhi", "Active", 3),
    Employee(44, "Tanya", "Mundra", "tanya.mundra@google.com", "Legal", "Paralegal", "London", "Not started", 5),
    Employee(45, "Urvashi", "Bora", "urvashi.bora@betatech.com", "HR", "Assistant", "Boston", "Active", 2),
    Employee(46, "Varun", "Kulshreshtha", "varun.kulshreshtha@infosys.com", "Engineering", "Developer", "Hyderabad", "Terminated", 3),
    Employee(47, "Waseem", "Ali", "waseem.ali@tcs.com", "Sales", "Executive", "Kolkata", "Active", 4),
    Employee(48, "Xahra", "Iqbal", "xahra.iqbal@google.com", "QA", "Lead", "Zurich", "Active", 5),
    Employee(49, "Yamini", "Shukla", "yamini.shukla@acmecorp.com", "Marketing", "Executive", "Austin", "Not started", 1),
    Employee(50, "Zeeshan", "Haider", "zeeshan.haider@betatech.com", "Engineering", "Architect", "Chicago", "Active", 2),
    Employee(51, "Aaliya", "Choudhary", "aaliya.choudhary@infosys.com", "Support", "Engineer", "Mysore", "Terminated", 3),
    Employee(52, "Bharat", "Joshi", "bharat.joshi@tcs.com", "Admin", "Coordinator", "Mumbai", "Active", 4),
    Employee(53, "Chaya", "Reddy", "chaya.reddy@google.com", "AI", "Scientist", "Mountain View", "Not started", 5),
    Employee(54, "Devika", "Singhania", "devika.singhania@acmecorp.com", "Engineering", "Tester", "NY", "Active", 1),
    Employee(55, "Eshan", "Tripathi", "eshan.tripathi@betatech.com", "Finance", "Analyst", "Seattle", "Terminated", 2),
    Employee(56, "Firoz", "Shaikh", "firoz.shaikh@infosys.com", "IT", "Support Engineer", "Chennai", "Active", 3),
    Employee(57, "Garima", "Jain", "garima.jain@tcs.com", "Legal", "Advisor", "Delhi", "Active", 4),
    Employee(58, "Hrithik", "Seth", "hrithik.seth@google.com", "Sales", "Executive", "London", "Active", 5),
    Employee(59, "Ipsita", "Sen", "ipsita.sen@acmecorp.com", "HR", "Recruiter", "Houston", "Terminated", 1),
    Employee(60, "Jitesh", "Khandelwal", "jitesh.khandelwal@betatech.com", "Engineering", "Developer", "Atlanta", "Not started", 2),
]
